# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Mello' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Mello
  pod 'Firebase/Core'

end

target 'MelloEx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MelloEx
  pod 'Firebase/Core'

end
