export const GET_FEEDO_LIST_PENDING = 'GET_FEEDO_LIST_PENDING'
export const GET_FEEDO_LIST_FULFILLED = 'GET_FEEDO_LIST_FULFILLED'
export const GET_FEEDO_LIST_REJECTED = 'GET_FEEDO_LIST_REJECTED'

export const PIN_FEED_PENDING = 'PIN_FEED_PENDING'
export const PIN_FEED_FULFILLED = 'PIN_FEED_FULFILLED'
export const PIN_FEED_REJECTED = 'PIN_FEED_REJECTED'

export const UNPIN_FEED_PENDING = 'UNPIN_FEED_PENDING'
export const UNPIN_FEED_FULFILLED = 'UNPIN_FEED_FULFILLED'
export const UNPIN_FEED_REJECTED = 'UNPIN_FEED_REJECTED'

export const DEL_FEED_PENDING = 'DEL_FEED_PENDING'
export const DEL_FEED_FULFILLED = 'DEL_FEED_FULFILLED'
export const DEL_FEED_REJECTED = 'DEL_FEED_REJECTED'

export const ARCHIVE_FEED_PENDING = 'ARCHIVE_FEED_PENDING'
export const ARCHIVE_FEED_FULFILLED = 'ARCHIVE_FEED_FULFILLED'
export const ARCHIVE_FEED_REJECTED = 'ARCHIVE_FEED_REJECTED'

export const DUPLICATE_FEED_PENDING = 'DUPLICATE_FEED_PENDING'
export const DUPLICATE_FEED_FULFILLED = 'DUPLICATE_FEED_FULFILLED'
export const DUPLICATE_FEED_REJECTED = 'DUPLICATE_FEED_REJECTED'

export const GET_FEED_DETAIL_PENDING = 'GET_FEED_DETAIL_PENDING'
export const GET_FEED_DETAIL_FULFILLED = 'GET_FEED_DETAIL_FULFILLED'
export const GET_FEED_DETAIL_REJECTED = 'GET_FEED_DETAIL_REJECTED'
