export const ADD_DUMMY_FEED = 'ADD_DUMMY_FEED'
export const REMOVE_DUMMY_FEED = 'REMOVE_DUMMY_FEED'
export const SET_FEED_DETAIL_ACTION = 'SET_FEED_DETAIL_ACTION'

export const GET_FEEDO_LIST_PENDING = 'GET_FEEDO_LIST_PENDING'
export const GET_FEEDO_LIST_FULFILLED = 'GET_FEEDO_LIST_FULFILLED'
export const GET_FEEDO_LIST_REJECTED = 'GET_FEEDO_LIST_REJECTED'

export const GET_INVITED_FEEDO_LIST_PENDING = 'GET_INVITED_FEEDO_LIST_PENDING'
export const GET_INVITED_FEEDO_LIST_FULFILLED = 'GET_INVITED_FEEDO_LIST_FULFILLED'
export const GET_INVITED_FEEDO_LIST_REJECTED = 'GET_INVITED_FEEDO_LIST_REJECTED'

export const PIN_FEED_PENDING = 'PIN_FEED_PENDING'
export const PIN_FEED_FULFILLED = 'PIN_FEED_FULFILLED'
export const PIN_FEED_REJECTED = 'PIN_FEED_REJECTED'

export const UNPIN_FEED_PENDING = 'UNPIN_FEED_PENDING'
export const UNPIN_FEED_FULFILLED = 'UNPIN_FEED_FULFILLED'
export const UNPIN_FEED_REJECTED = 'UNPIN_FEED_REJECTED'

export const DEL_FEED_PENDING = 'DEL_FEED_PENDING'
export const DEL_FEED_FULFILLED = 'DEL_FEED_FULFILLED'
export const DEL_FEED_REJECTED = 'DEL_FEED_REJECTED'

export const ARCHIVE_FEED_PENDING = 'ARCHIVE_FEED_PENDING'
export const ARCHIVE_FEED_FULFILLED = 'ARCHIVE_FEED_FULFILLED'
export const ARCHIVE_FEED_REJECTED = 'ARCHIVE_FEED_REJECTED'

export const DUPLICATE_FEED_PENDING = 'DUPLICATE_FEED_PENDING'
export const DUPLICATE_FEED_FULFILLED = 'DUPLICATE_FEED_FULFILLED'
export const DUPLICATE_FEED_REJECTED = 'DUPLICATE_FEED_REJECTED'

export const GET_FEED_DETAIL_PENDING = 'GET_FEED_DETAIL_PENDING'
export const GET_FEED_DETAIL_FULFILLED = 'GET_FEED_DETAIL_FULFILLED'
export const GET_FEED_DETAIL_REJECTED = 'GET_FEED_DETAIL_REJECTED'

export const ADD_FILTER_TAG = 'ADD_FILTER_TAG'

export const GET_ARCHIVED_FEED_PENDING = 'GET_ARCHIVED_FEED_PENDING'
export const GET_ARCHIVED_FEED_FULFILLED = 'GET_ARCHIVED_FEED_FULFILLED'
export const GET_ARCHIVED_FEED_REJECTED = 'GET_ARCHIVED_FEED_REJECTED'

export const RESTORE_ARCHIVE_FEED_PENDING = 'RESTORE_ARCHIVE_FEED_PENDING'
export const RESTORE_ARCHIVE_FEED_FULFILLED = 'RESTORE_ARCHIVE_FEED_FULFILLED'
export const RESTORE_ARCHIVE_FEED_REJECTED = 'RESTORE_ARCHIVE_FEED_REJECTED'

export const CREATE_FEED_PENDING = 'CREATE_FEED_PENDING'
export const CREATE_FEED_FULFILLED = 'CREATE_FEED_FULFILLED'
export const CREATE_FEED_REJECTED = 'CREATE_FEED_REJECTED'

export const UPDATE_FEED_PENDING = 'UPDATE_FEED_PENDING'
export const UPDATE_FEED_FULFILLED = 'UPDATE_FEED_FULFILLED'
export const UPDATE_FEED_REJECTED = 'UPDATE_FEED_REJECTED'

export const DELETE_FEED_PENDING = 'DELETE_FEED_PENDING'
export const DELETE_FEED_FULFILLED = 'DELETE_FEED_FULFILLED'
export const DELETE_FEED_REJECTED = 'DELETE_FEED_REJECTED'

export const SET_CURRENT_FEED = 'SET_CURRENT_FEED'

export const GET_FILE_UPLOAD_URL_PENDING = 'GET_FILE_UPLOAD_URL_PENDING'
export const GET_FILE_UPLOAD_URL_FULFILLED = 'GET_FILE_UPLOAD_URL_FULFILLED'
export const GET_FILE_UPLOAD_URL_REJECTED = 'GET_FILE_UPLOAD_URL_REJECTED'

export const UPLOAD_FILE_PENDING = 'UPLOAD_FILE_PENDING'
export const UPLOAD_FILE_FULFILLED = 'UPLOAD_FILE_FULFILLED'
export const UPLOAD_FILE_REJECTED = 'UPLOAD_FILE_REJECTED'

export const ADD_FILE_PENDING = 'ADD_FILE_PENDING'
export const ADD_FILE_FULFILLED = 'ADD_FILE_FULFILLED'
export const ADD_FILE_REJECTED = 'ADD_FILE_REJECTED'

export const DELETE_FILE_PENDING = 'DELETE_FILE_PENDING'
export const DELETE_FILE_FULFILLED = 'DELETE_FILE_FULFILLED'
export const DELETE_FILE_REJECTED = 'DELETE_FILE_REJECTED'

export const GET_USER_TAGS_PENDING = 'GET_USER_TAGS_PENDING'
export const GET_USER_TAGS_FULFILLED = 'GET_USER_TAGS_FULFILLED'
export const GET_USER_TAGS_REJECTED = 'GET_USER_TAGS_REJECTED'

export const CREATE_USER_TAG_PENDING = 'CREATE_USER_TAG_PENDING'
export const CREATE_USER_TAG_FULFILLED = 'CREATE_USER_TAG_FULFILLED'
export const CREATE_USER_TAG_REJECTED = 'CREATE_USER_TAG_REJECTED'

export const ADD_HUNT_TAG_PENDING = 'ADD_HUNT_TAG_PENDING'
export const ADD_HUNT_TAG_FULFILLED = 'ADD_HUNT_TAG_FULFILLED'
export const ADD_HUNT_TAG_REJECTED = 'ADD_HUNT_TAG_REJECTED'

export const REMOVE_HUNT_TAG_PENDING = 'REMOVE_HUNT_TAG_PENDING'
export const REMOVE_HUNT_TAG_FULFILLED = 'REMOVE_HUNT_TAG_FULFILLED'
export const REMOVE_HUNT_TAG_REJECTED = 'REMOVE_HUNT_TAG_REJECTED'

export const UPDATE_SHARING_PREFERENCES_PENDING = 'UPDATE_SHARING_PREFERENCES_PENDING'
export const UPDATE_SHARING_PREFERENCES_FULFILLED = 'UPDATE_SHARING_PREFERENCES_FULFILLED'
export const UPDATE_SHARING_PREFERENCES_REJECTED = 'UPDATE_SHARING_PREFERENCES_REJECTED'

export const DELETE_INVITEE_PENDING = 'DELETE_INVITEE_PENDING'
export const DELETE_INVITEE_FULFILLED = 'DELETE_INVITEE_FULFILLED'
export const DELETE_INVITEE_REJECTED = 'DELETE_INVITEE_REJECTED'

export const UPDATE_INVITEE_PERMISSION_PENDING = 'UPDATE_INVITEE_PERMISSION_PENDING'
export const UPDATE_INVITEE_PERMISSION_FULFILLED = 'UPDATE_INVITEE_PERMISSION_FULFILLED'
export const UPDATE_INVITEE_PERMISSION_REJECTED = 'UPDATE_INVITEE_PERMISSION_REJECTED'

export const INVITE_HUNT_PENDING = 'INVITE_HUNT_PENDING'
export const INVITE_HUNT_FULFILLED = 'INVITE_HUNT_FULFILLED'
export const INVITE_HUNT_REJECTED = 'INVITE_HUNT_REJECTED'

export const LEAVE_FEED_PENDING = 'LEAVE_FEED_PENDING'
export const LEAVE_FEED_FULFILLED = 'LEAVE_FEED_FULFILLED'
export const LEAVE_FEED_REJECTED = 'LEAVE_FEED_REJECTED'

export const UPDTE_FEED_INVITATION_PENDING = 'UPDTE_FEED_INVITATION_PENDING'
export const UPDTE_FEED_INVITATION_FULFILLED = 'UPDTE_FEED_INVITATION_FULFILLED'
export const UPDTE_FEED_INVITATION_REJECTED = 'UPDTE_FEED_INVITATION_REJECTED'

export const GET_ACTIVITY_FEED_PENDING = 'GET_ACTIVITY_FEED_PENDING'
export const GET_ACTIVITY_FEED_FULFILLED = 'GET_ACTIVITY_FEED_FULFILLED'
export const GET_ACTIVITY_FEED_REJECTED = 'GET_ACTIVITY_FEED_REJECTED'

export const READ_ALL_ACTIVITY_FEED_PENDING = 'READ_ALL_ACTIVITY_FEED_PENDING'
export const READ_ALL_ACTIVITY_FEED_FULFILLED = 'READ_ALL_ACTIVITY_FEED_FULFILLED'
export const READ_ALL_ACTIVITY_FEED_REJECTED = 'READ_ALL_ACTIVITY_FEED_REJECTED'

export const READ_ACTIVITY_FEED_PENDING = 'READ_ACTIVITY_FEED_PENDING'
export const READ_ACTIVITY_FEED_FULFILLED = 'READ_ACTIVITY_FEED_FULFILLED'
export const READ_ACTIVITY_FEED_REJECTED = 'READ_ACTIVITY_FEED_REJECTED'

export const DEL_ACTIVITY_FEED_PENDING = 'DEL_ACTIVITY_FEED_PENDING'
export const DEL_ACTIVITY_FEED_FULFILLED = 'DEL_ACTIVITY_FEED_FULFILLED'
export const DEL_ACTIVITY_FEED_REJECTED = 'DEL_ACTIVITY_FEED_REJECTED'

export const DEL_DUMMY_CARD = 'DEL_DUMMY_CARD'
export const MOVE_DUMMY_CARD = 'MOVE_DUMMY_CARD'

// Pubnub event types
export const PUBNUB_DELETE_FEED = 'PUBNUB_DELETE_FEED'

export const PUBNUB_GET_FEED_DETAIL_PENDING = 'PUBNUB_GET_FEED_DETAIL_PENDING'
export const PUBNUB_GET_FEED_DETAIL_FULFILLED = 'PUBNUB_GET_FEED_DETAIL_FULFILLED'
export const PUBNUB_GET_FEED_DETAIL_REJECTED = 'PUBNUB_GET_FEED_DETAIL_REJECTED'

export const PUBNUB_LIKE_CARD_FULFILLED = 'PUBNUB_LIKE_CARD_FULFILLED'
export const PUBNUB_UNLIKE_CARD_FULFILLED = 'PUBNUB_UNLIKE_CARD_FULFILLED'

export const PUBNUB_DELETE_INVITEE_FULFILLED = 'PUBNUB_DELETE_INVITEE_FULFILLED'
export const PUBNUB_DELETE_OTHER_INVITEE_FULFILLED = 'PUBNUB_DELETE_OTHER_INVITEE_FULFILLED'

export const GET_ACTIVITY_FEED_VISITED_PENDING = 'GET_ACTIVITY_FEED_VISITED_PENDING'
export const GET_ACTIVITY_FEED_VISITED_FULFILLED = 'GET_ACTIVITY_FEED_VISITED_FULFILLED'
export const GET_ACTIVITY_FEED_VISITED_REJECTED = 'GET_ACTIVITY_FEED_VISITED_REJECTED'

export const PUBNUB_MOVE_IDEA_FULFILLED = 'PUBNUB_MOVE_IDEA_FULFILLED'