export const GET_FEEDO_LIST_PENDING = 'GET_FEEDO_LIST_PENDING'
export const GET_FEEDO_LIST_FULFILLED = 'GET_FEEDO_LIST_FULFILLED'
export const GET_FEEDO_LIST_REJECTED = 'GET_FEEDO_LIST_REJECTED'

export const PIN_FEED_PENDING = 'PIN_FEED_PENDING'
export const PIN_FEED_FULFILLED = 'PIN_FEED_FULFILLED'
export const PIN_FEED_REJECTED = 'PIN_FEED_REJECTED'