export const USER_LOOKUP_PENDING = 'USER_LOOKUP_PENDING'
export const USER_LOOKUP_FULFILLED = 'USER_LOOKUP_FULFILLED'
export const USER_LOOKUP_REJECTED = 'USER_LOOKUP_REJECTED'

export const USER_SIGNIN_PENDING = 'USER_SIGNIN_PENDING'
export const USER_SIGNIN_FULFILLED = 'USER_SIGNIN_FULFILLED'
export const USER_SIGNIN_REJECTED = 'USER_SIGNIN_REJECTED'

export const USER_SIGNUP_PENDING = 'USER_SIGNUP_PENDING'
export const USER_SIGNUP_FULFILLED = 'USER_SIGNUP_FULFILLED'
export const USER_SIGNUP_REJECTED = 'USER_SIGNUP_REJECTED'

export const USER_SIGNOUT_PENDING = 'USER_SIGNOUT_PENDING'
export const USER_SIGNOUT_FULFILLED = 'USER_SIGNOUT_FULFILLED'
export const USER_SIGNOUT_REJECTED = 'USER_SIGNOUT_REJECTED'

export const GET_CONTACT_LIST_PENDING = 'GET_CONTACT_LIST_PENDING'
export const GET_CONTACT_LIST_FULFILLED = 'GET_CONTACT_LIST_FULFILLED'
export const GET_CONTACT_LIST_REJECTED = 'GET_CONTACT_LIST_REJECTED'

export const SET_USER_INFO = 'SET_USER_INFO'