export const USER_LOOKUP_PENDING = 'USER_LOOKUP_PENDING'
export const USER_LOOKUP_FULFILLED = 'USER_LOOKUP_FULFILLED'
export const USER_LOOKUP_REJECTED = 'USER_LOOKUP_REJECTED'

export const USER_SIGNIN_PENDING = 'USER_SIGNIN_PENDING'
export const USER_SIGNIN_FULFILLED = 'USER_SIGNIN_FULFILLED'
export const USER_SIGNIN_REJECTED = 'USER_SIGNIN_REJECTED'

export const USER_SIGNUP_PENDING = 'USER_SIGNUP_PENDING'
export const USER_SIGNUP_FULFILLED = 'USER_SIGNUP_FULFILLED'
export const USER_SIGNUP_REJECTED = 'USER_SIGNUP_REJECTED'

export const USER_SIGNOUT_PENDING = 'USER_SIGNOUT_PENDING'
export const USER_SIGNOUT_FULFILLED = 'USER_SIGNOUT_FULFILLED'
export const USER_SIGNOUT_REJECTED = 'USER_SIGNOUT_REJECTED'

export const GET_CONTACT_LIST_PENDING = 'GET_CONTACT_LIST_PENDING'
export const GET_CONTACT_LIST_FULFILLED = 'GET_CONTACT_LIST_FULFILLED'
export const GET_CONTACT_LIST_REJECTED = 'GET_CONTACT_LIST_REJECTED'

export const GET_USER_IMAGE_URL_PENDING = 'GET_USER_IMAGE_URL_PENDING'
export const GET_USER_IMAGE_URL_FULFILLED = 'GET_USER_IMAGE_URL_FULFILLED'
export const GET_USER_IMAGE_URL_REJECTED = 'GET_USER_IMAGE_URL_REJECTED'

export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_HOME_LIST_TYPE = 'SET_HOME_LIST_TYPE'
export const SAVE_FLOW_VIEW_PREFERENCE = 'SAVE_FLOW_VIEW_PREFERENCE'

export const GET_USER_SESSION_PENDING = 'GET_USER_SESSION_PENDING'
export const GET_USER_SESSION_FULFILLED = 'GET_USER_SESSION_FULFILLED'
export const GET_USER_SESSION_REJECTED = 'GET_USER_SESSION_REJECTED'

export const RESEND_CONFIRMATION_EMAIL_PENDING = 'RESEND_CONFIRMATION_EMAIL_PENDING'
export const RESEND_CONFIRMATION_EMAIL_FULFILLED = 'RESEND_CONFIRMATION_EMAIL_FULFILLED'
export const RESEND_CONFIRMATION_EMAIL_REJECTED = 'RESEND_CONFIRMATION_EMAIL_REJECTED'

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING'
export const UPDATE_PROFILE_FULFILLED = 'UPDATE_PROFILE_FULFILLED'
export const UPDATE_PROFILE_REJECTED = 'UPDATE_PROFILE_REJECTED'

export const UPDATE_PASSWORD_PENDING = 'UPDATE_PASSWORD_PENDING'
export const UPDATE_PASSWORD_FULFILLED = 'UPDATE_PASSWORD_FULFILLED'
export const UPDATE_PASSWORD_REJECTED = 'UPDATE_PASSWORD_REJECTED'

export const USER_CONFIRM_ACCOUNT_PENDING = 'USER_CONFIRM_ACCOUNT_PENDING'
export const USER_CONFIRM_ACCOUNT_FULFILLED = 'USER_CONFIRM_ACCOUNT_FULFILLED'
export const USER_CONFIRM_ACCOUNT_REJECTED = 'USER_CONFIRM_ACCOUNT_REJECTED'

export const SEND_RESET_PASSWORD_EMAIL_PENDING = 'SEND_RESET_PASSWORD_EMAIL_PENDING'
export const SEND_RESET_PASSWORD_EMAIL_FULFILLED = 'SEND_RESET_PASSWORD_EMAIL_FULFILLED'
export const SEND_RESET_PASSWORD_EMAIL_REJECTED = 'SEND_RESET_PASSWORD_EMAIL_REJECTED'

export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING'
export const RESET_PASSWORD_FULFILLED = 'RESET_PASSWORD_FULFILLED'
export const RESET_PASSWORD_REJECTED = 'RESET_PASSWORD_REJECTED'

export const VALIDATE_INVITE_PENDING = 'VALIDATE_INVITE_PENDING'
export const VALIDATE_INVITE_FULFILLED = 'VALIDATE_INVITE_FULFILLED'
export const VALIDATE_INVITE_REJECTED = 'VALIDATE_INVITE_REJECTED'

export const COMPLETE_INVITE_PENDING = 'COMPLETE_INVITE_PENDING'
export const COMPLETE_INVITE_FULFILLED = 'COMPLETE_INVITE_FULFILLED'
export const COMPLETE_INVITE_REJECTED = 'COMPLETE_INVITE_REJECTED'

export const ADD_DEVICE_TOKEN_PENDING = 'ADD_DEVICE_TOKEN_PENDING'
export const ADD_DEVICE_TOKEN_FULFILLED = 'ADD_DEVICE_TOKEN_FULFILLED'
export const ADD_DEVICE_TOKEN_REJECTED = 'ADD_DEVICE_TOKEN_REJECTED'

export const UPDATE_DEVICE_TOKEN_PENDING = 'UPDATE_DEVICE_TOKEN_PENDING'
export const UPDATE_DEVICE_TOKEN_FULFILLED = 'UPDATE_DEVICE_TOKEN_FULFILLED'
export const UPDATE_DEVICE_TOKEN_REJECTED = 'UPDATE_DEVICE_TOKEN_REJECTED'

export const DELETE_PROFILE_PHOTO_REQUEST = 'DELETE_PROFILE_PHOTO_REQUEST'
export const DELETE_PROFILE_PHOTO_FULFILLED = 'DELETE_PROFILE_PHOTO_FULFILLED'
export const DELETE_PROFILE_PHOTO_REJECTED = 'DELETE_PROFILE_PHOTO_REJECTED'

export const UPLOAD_FILE_PENDING = 'UPLOAD_FILE_PENDING'
export const UPLOAD_FILE_FULFILLED = 'UPLOAD_FILE_FULFILLED'
export const UPLOAD_FILE_REJECTED = 'UPLOAD_FILE_REJECTED'

export const SHOW_CLIPBOARD_TOASTER = 'SHOW_CLIPBOARD_TOASTER'
export const CLOSE_CLIPBOARD_TOASTER = 'CLOSE_CLIPBOARD_TOASTER'

export const USER_GOOGLE_SIGNIN_PENDING = 'USER_GOOGLE_SIGNIN_PENDING'
export const USER_GOOGLE_SIGNIN_FULFILLED = 'USER_GOOGLE_SIGNIN_FULFILLED'
export const USER_GOOGLE_SIGNIN_REJECTED = 'USER_GOOGLE_SIGNIN_REJECTED'