export const CREATE_FEED_PENDING = 'CREATE_FEED_PENDING'
export const CREATE_FEED_FULFILLED = 'CREATE_FEED_FULFILLED'
export const CREATE_FEED_REJECTED = 'CREATE_FEED_REJECTED'

export const UPDATE_FEED_PENDING = 'UPDATE_FEED_PENDING'
export const UPDATE_FEED_FULFILLED = 'UPDATE_FEED_FULFILLED'
export const UPDATE_FEED_REJECTED = 'UPDATE_FEED_REJECTED'

export const DELETE_FEED_PENDING = 'DELETE_FEED_PENDING'
export const DELETE_FEED_FULFILLED = 'DELETE_FEED_FULFILLED'
export const DELETE_FEED_REJECTED = 'DELETE_FEED_REJECTED'
