export const CREATE_FEED_PENDING = 'CREATE_FEED_PENDING'
export const CREATE_FEED_FULFILLED = 'CREATE_FEED_FULFILLED'
export const CREATE_FEED_REJECTED = 'CREATE_FEED_REJECTED'

export const UPDATE_FEED_PENDING = 'UPDATE_FEED_PENDING'
export const UPDATE_FEED_FULFILLED = 'UPDATE_FEED_FULFILLED'
export const UPDATE_FEED_REJECTED = 'UPDATE_FEED_REJECTED'

export const DELETE_FEED_PENDING = 'DELETE_FEED_PENDING'
export const DELETE_FEED_FULFILLED = 'DELETE_FEED_FULFILLED'
export const DELETE_FEED_REJECTED = 'DELETE_FEED_REJECTED'

export const GET_FILE_UPLOAD_URL_PENDING = 'GET_FILE_UPLOAD_URL_PENDING'
export const GET_FILE_UPLOAD_URL_FULFILLED = 'GET_FILE_UPLOAD_URL_FULFILLED'
export const GET_FILE_UPLOAD_URL_REJECTED = 'GET_FILE_UPLOAD_URL_REJECTED'

export const UPLOAD_FILE_PENDING = 'UPLOAD_FILE_PENDING'
export const UPLOAD_FILE_FULFILLED = 'UPLOAD_FILE_FULFILLED'
export const UPLOAD_FILE_REJECTED = 'UPLOAD_FILE_REJECTED'
