export const CREATE_FEED_PENDING = 'CREATE_FEED_PENDING'
export const CREATE_FEED_FULFILLED = 'CREATE_FEED_FULFILLED'
export const CREATE_FEED_REJECTED = 'CREATE_FEED_REJECTED'

export const UPDATE_FEED_PENDING = 'UPDATE_FEED_PENDING'
export const UPDATE_FEED_FULFILLED = 'UPDATE_FEED_FULFILLED'
export const UPDATE_FEED_REJECTED = 'UPDATE_FEED_REJECTED'

export const DELETE_FEED_PENDING = 'DELETE_FEED_PENDING'
export const DELETE_FEED_FULFILLED = 'DELETE_FEED_FULFILLED'
export const DELETE_FEED_REJECTED = 'DELETE_FEED_REJECTED'

export const GET_FILE_UPLOAD_URL_PENDING = 'GET_FILE_UPLOAD_URL_PENDING'
export const GET_FILE_UPLOAD_URL_FULFILLED = 'GET_FILE_UPLOAD_URL_FULFILLED'
export const GET_FILE_UPLOAD_URL_REJECTED = 'GET_FILE_UPLOAD_URL_REJECTED'

export const UPLOAD_FILE_PENDING = 'UPLOAD_FILE_PENDING'
export const UPLOAD_FILE_FULFILLED = 'UPLOAD_FILE_FULFILLED'
export const UPLOAD_FILE_REJECTED = 'UPLOAD_FILE_REJECTED'

export const ADD_FILE_PENDING = 'ADD_FILE_PENDING'
export const ADD_FILE_FULFILLED = 'ADD_FILE_FULFILLED'
export const ADD_FILE_REJECTED = 'ADD_FILE_REJECTED'

export const DELETE_FILE_PENDING = 'DELETE_FILE_PENDING'
export const DELETE_FILE_FULFILLED = 'DELETE_FILE_FULFILLED'
export const DELETE_FILE_REJECTED = 'DELETE_FILE_REJECTED'

export const GET_USER_TAGS_PENDING = 'GET_USER_TAGS_PENDING'
export const GET_USER_TAGS_FULFILLED = 'GET_USER_TAGS_FULFILLED'
export const GET_USER_TAGS_REJECTED = 'GET_USER_TAGS_REJECTED'

export const CREATE_USER_TAG_PENDING = 'CREATE_USER_TAG_PENDING'
export const CREATE_USER_TAG_FULFILLED = 'CREATE_USER_TAG_FULFILLED'
export const CREATE_USER_TAG_REJECTED = 'CREATE_USER_TAG_REJECTED'

export const ADD_HUNT_TAG_PENDING = 'ADD_HUNT_TAG_PENDING'
export const ADD_HUNT_TAG_FULFILLED = 'ADD_HUNT_TAG_FULFILLED'
export const ADD_HUNT_TAG_REJECTED = 'ADD_HUNT_TAG_REJECTED'

export const REMOVE_HUNT_TAG_PENDING = 'REMOVE_HUNT_TAG_PENDING'
export const REMOVE_HUNT_TAG_FULFILLED = 'REMOVE_HUNT_TAG_FULFILLED'
export const REMOVE_HUNT_TAG_REJECTED = 'REMOVE_HUNT_TAG_REJECTED'


//
export const GET_FEED_DETAIL_PENDING = 'GET_FEED_DETAIL_PENDING'
export const GET_FEED_DETAIL_FULFILLED = 'GET_FEED_DETAIL_FULFILLED'
export const GET_FEED_DETAIL_REJECTED = 'GET_FEED_DETAIL_REJECTED'
