export const CREATE_CARD_PENDING = 'CREATE_CARD_PENDING'
export const CREATE_CARD_FULFILLED = 'CREATE_CARD_FULFILLED'
export const CREATE_CARD_REJECTED = 'CREATE_CARD_REJECTED'

export const UPDATE_CARD_PENDING = 'UPDATE_CARD_PENDING'
export const UPDATE_CARD_FULFILLED = 'UPDATE_CARD_FULFILLED'
export const UPDATE_CARD_REJECTED = 'UPDATE_CARD_REJECTED'

export const DELETE_CARD_PENDING = 'DELETE_CARD_PENDING'
export const DELETE_CARD_FULFILLED = 'DELETE_CARD_FULFILLED'
export const DELETE_CARD_REJECTED = 'DELETE_CARD_REJECTED'

export const GET_FILE_UPLOAD_URL_PENDING = 'GET_FILE_UPLOAD_URL_PENDING'
export const GET_FILE_UPLOAD_URL_FULFILLED = 'GET_FILE_UPLOAD_URL_FULFILLED'
export const GET_FILE_UPLOAD_URL_REJECTED = 'GET_FILE_UPLOAD_URL_REJECTED'

export const UPLOAD_FILE_PENDING = 'UPLOAD_FILE_PENDING'
export const UPLOAD_FILE_FULFILLED = 'UPLOAD_FILE_FULFILLED'
export const UPLOAD_FILE_REJECTED = 'UPLOAD_FILE_REJECTED'

export const ADD_FILE_PENDING = 'ADD_FILE_PENDING'
export const ADD_FILE_FULFILLED = 'ADD_FILE_FULFILLED'
export const ADD_FILE_REJECTED = 'ADD_FILE_REJECTED'

export const DELETE_FILE_PENDING = 'DELETE_FILE_PENDING'
export const DELETE_FILE_FULFILLED = 'DELETE_FILE_FULFILLED'
export const DELETE_FILE_REJECTED = 'DELETE_FILE_REJECTED'