export const CREATE_CARD_PENDING = 'CREATE_CARD_PENDING'
export const CREATE_CARD_FULFILLED = 'CREATE_CARD_FULFILLED'
export const CREATE_CARD_REJECTED = 'CREATE_CARD_REJECTED'

export const UPDATE_CARD_PENDING = 'UPDATE_CARD_PENDING'
export const UPDATE_CARD_FULFILLED = 'UPDATE_CARD_FULFILLED'
export const UPDATE_CARD_REJECTED = 'UPDATE_CARD_REJECTED'

export const GET_CARD_PENDING = 'GET_CARD_PENDING'
export const GET_CARD_FULFILLED = 'GET_CARD_FULFILLED'
export const GET_CARD_REJECTED = 'GET_CARD_REJECTED'

export const SET_CURRENT_CARD = 'SET_CURRENT_CARD'

export const RESET_CARD_ERROR = 'RESET_CARD_ERROR'

export const DELETE_CARD_PENDING = 'DELETE_CARD_PENDING'
export const DELETE_CARD_FULFILLED = 'DELETE_CARD_FULFILLED'
export const DELETE_CARD_REJECTED = 'DELETE_CARD_REJECTED'

export const MOVE_CARD_PENDING = 'MOVE_CARD_PENDING'
export const MOVE_CARD_FULFILLED = 'MOVE_CARD_FULFILLED'
export const MOVE_CARD_REJECTED = 'MOVE_CARD_REJECTED'

export const GET_FILE_UPLOAD_URL_PENDING = 'GET_IDEA_FILE_UPLOAD_URL_PENDING'
export const GET_FILE_UPLOAD_URL_FULFILLED = 'GET_IDEA_FILE_UPLOAD_URL_FULFILLED'
export const GET_FILE_UPLOAD_URL_REJECTED = 'GET_IDEA_FILE_UPLOAD_URL_REJECTED'

export const UPLOAD_FILE_PENDING = 'UPLOAD_IDEA_FILE_PENDING'
export const UPLOAD_FILE_FULFILLED = 'UPLOAD_IDEA_FILE_FULFILLED'
export const UPLOAD_FILE_REJECTED = 'UPLOAD_IDEA_FILE_REJECTED'

export const ADD_FILE_PENDING = 'ADD_IDEA_FILE_PENDING'
export const ADD_FILE_FULFILLED = 'ADD_IDEA_FILE_FULFILLED'
export const ADD_FILE_REJECTED = 'ADD_IDEA_FILE_REJECTED'

export const DELETE_FILE_PENDING = 'DELETE_IDEA_FILE_PENDING'
export const DELETE_FILE_FULFILLED = 'DELETE_IDEA_FILE_FULFILLED'
export const DELETE_FILE_REJECTED = 'DELETE_IDEA_FILE_REJECTED'

export const SET_COVER_IMAGE_PENDING = 'SET_COVER_IMAGE_PENDING'
export const SET_COVER_IMAGE_FULFILLED = 'SET_COVER_IMAGE_FULFILLED'
export const SET_COVER_IMAGE_REJECTED = 'SET_COVER_IMAGE_REJECTED'

export const GET_OPEN_GRAPH_PENDING = 'GET_OPEN_GRAPH_PENDING'
export const GET_OPEN_GRAPH_FULFILLED = 'GET_OPEN_GRAPH_FULFILLED'
export const GET_OPEN_GRAPH_REJECTED = 'GET_OPEN_GRAPH_REJECTED'

export const LIKE_CARD_PENDING = 'LIKE_CARD_PENDING'
export const LIKE_CARD_FULFILLED = 'LIKE_CARD_FULFILLED'
export const LIKE_CARD_REJECTED = 'LIKE_CARD_REJECTED'

export const UNLIKE_CARD_PENDING = 'UNLIKE_CARD_PENDING'
export const UNLIKE_CARD_FULFILLED = 'UNLIKE_CARD_FULFILLED'
export const UNLIKE_CARD_REJECTED = 'UNLIKE_CARD_REJECTED'

export const GET_CARD_LIKES_PENDING = 'GET_CARD_LIKES_PENDING'
export const GET_CARD_LIKES_FULFILLED = 'GET_CARD_LIKES_FULFILLED'
export const GET_CARD_LIKES_REJECTED = 'GET_CARD_LIKES_REJECTED'

export const GET_CARD_COMMENTS_PENDING = 'GET_CARD_COMMENTS_PENDING'
export const GET_CARD_COMMENTS_FULFILLED = 'GET_CARD_COMMENTS_FULFILLED'
export const GET_CARD_COMMENTS_REJECTED = 'GET_CARD_COMMENTS_REJECTED'

export const ADD_CARD_COMMENT_PENDING = 'ADD_CARD_COMMENT_PENDING'
export const ADD_CARD_COMMENT_FULFILLED = 'ADD_CARD_COMMENT_FULFILLED'
export const ADD_CARD_COMMENT_REJECTED = 'ADD_CARD_COMMENT_REJECTED'

export const EDIT_CARD_COMMENT_PENDING = 'EDIT_CARD_COMMENT_PENDING'
export const EDIT_CARD_COMMENT_FULFILLED = 'EDIT_CARD_COMMENT_FULFILLED'
export const EDIT_CARD_COMMENT_REJECTED = 'EDIT_CARD_COMMENT_REJECTED'

export const DELETE_CARD_COMMENT_PENDING = 'DELETE_CARD_COMMENT_PENDING'
export const DELETE_CARD_COMMENT_FULFILLED = 'DELETE_CARD_COMMENT_FULFILLED'
export const DELETE_CARD_COMMENT_REJECTED = 'DELETE_CARD_COMMENT_REJECTED'

export const ADD_LINK_PENDING = 'ADD_LINK_PENDING'
export const ADD_LINK_FULFILLED = 'ADD_LINK_FULFILLED'
export const ADD_LINK_REJECTED = 'ADD_LINK_REJECTED'

export const DELETE_LINK_PENDING = 'DELETE_LINK_PENDING'
export const DELETE_LINK_FULFILLED = 'DELETE_LINK_FULFILLED'
export const DELETE_LINK_REJECTED = 'DELETE_LINK_REJECTED'

export const ADD_SHARE_EXTENSION_CARD_PENDING = 'ADD_SHARE_EXTENSION_CARD_PENDING'
export const ADD_SHARE_EXTENSION_CARD_FULFILLED = 'ADD_SHARE_EXTENSION_CARD_FULFILLED'
export const ADD_SHARE_EXTENSION_CARD_REJECTED = 'ADD_SHARE_EXTENSION_CARD_REJECTED'